[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#10A37F"
backgroundColor = "#343541"
secondaryBackgroundColor = "#444654"
textColor = "#ECECF1"

[runner]
# Entry point file
main = "app/app.py"